apiVersion: v1
kind: Service
metadata:
  name: request-service
spec:
  selector:
    app: request-service
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 30002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-service
spec:
  selector:
    matchLabels:
      app: request-service
  replicas: 1
  template:
    metadata:
      labels:
        app: request-service
    spec:
      containers:
        - name: server
          image: ainkamalinka26/request-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082

---